'use client';

import type { ModelNote, UnrecognisedIngredient } from '@allergy-checker/shared';
import { useEffect, useState } from 'react';
import { ApiError, describeUnrecognised } from '../lib/api';

/** Matches the API's cap, so one request always suffices. */
const MAX_NAMES = 25;

/**
 * What a language model says about the names the reference data could not identify.
 *
 * Asked for, never fetched unprompted: it spends quota, and a user who does not ask should
 * not be shown model text beside a verdict. Everything here is kept visibly apart from
 * the verdict and the annotated list. A proposal can reach a verdict only one way — the
 * user substitutes a proposed name the reference data does hold, and the label is checked
 * again against the cited data like anything they typed.
 */
export function ModelNotes({
  unmatched,
  model,
  onSubstitute,
}: {
  unmatched: UnrecognisedIngredient[];
  model: string;
  onSubstitute: (printed: string, inciName: string) => void;
}) {
  const names = unmatched.slice(0, MAX_NAMES).map((entry) => entry.rawText);
  const asked = names.join('\n');
  const [notes, setNotes] = useState<ModelNote[] | null>(null);
  const [pending, setPending] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // A new analysis is a new question; notes on the previous label must not linger.
  useEffect(() => {
    setNotes(null);
    setError(null);
  }, [asked]);

  async function ask() {
    setPending(true);
    setError(null);
    try {
      setNotes((await describeUnrecognised(names)).notes);
    } catch (cause) {
      setError(cause instanceof ApiError ? cause.message : 'The notes could not be fetched.');
    } finally {
      setPending(false);
    }
  }

  const answered = new Set(notes?.map((note) => note.rawText));
  const silent = notes ? names.filter((name) => !answered.has(name)) : [];

  return (
    <section className="mt-12 border-t border-line pt-8">
      <h2 className="font-serif text-2xl">Model notes on the unrecognised names</h2>
      <p className="mt-2 text-sm leading-relaxed text-muted">
        Generated by {model}. Not taken from the reference data and not checked against any rule, so
        they cannot change the verdict above. Where a proposed name is in the reference data, it can
        be substituted into the label and checked properly.
      </p>

      {notes === null ? (
        <button
          type="button"
          onClick={() => void ask()}
          disabled={pending}
          className="mt-5 rounded-md border border-line px-4 py-2 text-sm hover:border-muted disabled:opacity-40"
        >
          {pending
            ? 'Asking…'
            : `Ask ${model} about ${names.length} ${names.length === 1 ? 'name' : 'names'}`}
        </button>
      ) : (
        <ul className="mt-5 divide-y divide-line">
          {notes.map(({ rawText, proposedInciName, summary, confidence, resolvesTo }) => (
            <li key={rawText} className="border-l-2 border-l-line py-4 pl-4">
              <p className="font-medium break-words">{rawText}</p>
              <p className="mt-1 text-sm">
                {proposedInciName ? (
                  <>
                    Proposed INCI name: <span className="break-words">{proposedInciName}</span>
                  </>
                ) : (
                  'No INCI name proposed.'
                )}{' '}
                <span className="text-muted">· {confidence} confidence</span>
              </p>
              {summary && <p className="mt-1 text-sm text-muted">{summary}</p>}
              {resolvesTo ? (
                <div className="mt-2 flex flex-wrap items-center gap-x-4 gap-y-2">
                  <p className="text-sm">{resolvesTo.inciName} is in the reference data.</p>
                  <button
                    type="button"
                    onClick={() => onSubstitute(rawText, resolvesTo.inciName)}
                    className="rounded-md border border-line px-3 py-1.5 text-sm hover:border-muted"
                  >
                    Substitute it and check again
                  </button>
                </div>
              ) : (
                proposedInciName && (
                  <p className="mt-2 text-sm text-muted">
                    That name is not in the reference data either, so it still cannot be checked.
                  </p>
                )
              )}
            </li>
          ))}
        </ul>
      )}

      {silent.length > 0 && (
        <p className="mt-3 text-sm text-muted">No note was returned for {silent.join(', ')}.</p>
      )}
      {unmatched.length > MAX_NAMES && (
        <p className="mt-3 text-sm text-muted">
          Notes cover the first {MAX_NAMES} of {unmatched.length} unrecognised names.
        </p>
      )}
      {error && <p className="mt-3 text-sm text-avoid">{error}</p>}
    </section>
  );
}
